spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/*/v2.0
            user-email-attribute: email
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
            client-id: **
            client-secret: ***
            scope:
              - openid
              - email
              - profile